### ISSUE TITLE
[Forge 1.20.1] Mod is breaking JER Integration

### ISSUE THREAD

**Issue by vizthex123** [0rc1nus/Galosphere-Main#95]
Already reported it to the [JER devs](https://github.com/Janoeo/JER-Integration/issues/20), but he said it seems to be an issue with this mod so I figured I'd post here.

**Comment by AlasDiablo** [comment]
JER Integration not JER. ^^'

More information for 0rc1nus about the problem:

From what I have seen during my debug is that JER is trying to get every biome but when one of the galosphere biomes is called, the value of the registery key is null causing an unrecoverable crash.

I don't know if the problems are caused by me calling the registries system at the wrong time or if your mods have specific biomes.

Here is a small part of the log available in the issues on my addons.
```java
java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / galosphere:lichen_caves]
  at net.minecraft.core.RegistrySetBuilder$BuildState.m_255228_(RegistrySetBuilder.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23538!/:?]
  at net.minecraft.core.RegistrySetBuilder.m_255144_(RegistrySetBuilder.java:61) ~[client-1.20.1-20230612.114412-srg.jar%23538!/:?]
  at net.minecraft.data.registries.VanillaRegistries.m_255371_(VanillaRegistries.java:72) ~[client-1.20.1-20230612.114412-srg.jar%23538!/:?]
  // JER Biome hook
  at jeresources.api.util.BiomeHelper.getBiome(BiomeHelper.java:20) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
  at jeresources.api.restrictions.BiomeRestriction.<init>(BiomeRestriction.java:46) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
  at jeresources.api.restrictions.BiomeRestriction.<clinit>(BiomeRestriction.java:19) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
  at jeresources.api.restrictions.Restriction.<init>(Restriction.java:23) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
  at jeresources.api.restrictions.Restriction.<clinit>(Restriction.java:6) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
  at jeresources.entry.WorldGenEntry.<init>(WorldGenEntry.java:56) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
  at jeresources.compatibility.api.WorldGenRegistryImpl.register(WorldGenRegistryImpl.java:64) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
  // My mod hook to JER APi
  at fr.alasdiablo.jerintegration.util.JERIntegrationUtils.register(JERIntegrationUtils.java:20) ~[jerintegration-5.5.0.jar%23446!/:5.5.0]
```

**Comment by vizthex123** [comment]
> JER Integration not JER. ^^'
ah yeah, sorry. Changed the title.


> More information for 0rc1nus about the problem:
> 
> From what I have seen during my debug is that JER is trying to get every biome but when one of the galosphere biomes is called, the value of the registery key is null causing an unrecoverable crash.
> 
> I don't know if the problems are caused by me calling the registries system at the wrong time or if your mods have specific biomes.
> 
> Here is a small part of the log available in the issues on my addons.
> 
> ```java
> java.lang.IllegalStateException: Unreferenced key: ResourceKey[minecraft:worldgen/biome / galosphere:lichen_caves]
>   at net.minecraft.core.RegistrySetBuilder$BuildState.m_255228_(RegistrySetBuilder.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23538!/:?]
>   at net.minecraft.core.RegistrySetBuilder.m_255144_(RegistrySetBuilder.java:61) ~[client-1.20.1-20230612.114412-srg.jar%23538!/:?]
>   at net.minecraft.data.registries.VanillaRegistries.m_255371_(VanillaRegistries.java:72) ~[client-1.20.1-20230612.114412-srg.jar%23538!/:?]
>   // JER Biome hook
>   at jeresources.api.util.BiomeHelper.getBiome(BiomeHelper.java:20) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
>   at jeresources.api.restrictions.BiomeRestriction.<init>(BiomeRestriction.java:46) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
>   at jeresources.api.restrictions.BiomeRestriction.<clinit>(BiomeRestriction.java:19) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
>   at jeresources.api.restrictions.Restriction.<init>(Restriction.java:23) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
>   at jeresources.api.restrictions.Restriction.<clinit>(Restriction.java:6) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
>   at jeresources.entry.WorldGenEntry.<init>(WorldGenEntry.java:56) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
>   at jeresources.compatibility.api.WorldGenRegistryImpl.register(WorldGenRegistryImpl.java:64) ~[JustEnoughResources-1.20.1-1.4.0.247.jar%23449!/:1.4.0.247]
>   // My mod hook to JER APi
>   at fr.alasdiablo.jerintegration.util.JERIntegrationUtils.register(JERIntegrationUtils.java:20) ~[jerintegration-5.5.0.jar%23446!/:5.5.0]
> ```

yeah, i dunno either. That's why i reported it to both devs (sometimes mods just don't wanna work together unless you add an extra line or two of code saying to lol)

if it's not fixable, perhaps you and the JER Integration dev could just have Galosphere blacklisted as a workaround?

**Comment by zHawky** [comment]
Did some research and found a small workaround, if you install Aether along with the Lost Content addon you will get a working version of JER. 
Try this xD

**Comment by vizthex123** [comment]
> Did some research and found a small workaround, if you install Aether along with the Lost Content addon you will get a working version of JER. Try this xD

it doesn't fit the pack i'm making, but it's pretty funny that this is the workaround lol

**Comment by raffle2** [comment]
I have the same problem when Galosphere is installed, JEI and all other addons work except for JER, none of the categories appear.
- MC 1.20.1 - Forge 47.3.0
- Galosphere-1.20.1-1.4.1-Forge.jar
- JustEnoughResources-1.20.1-1.4.0.247.jar

**Comment by YaibaToKen** [comment]
Are there any news on this?

**Comment by zHawky** [comment]
> Are there any news on this?


Make a choice either Galosphere or JER

**Comment by raffle2** [comment]
> Are there any news on this?

Like suggested above, actually installing Aether along with the Lost Content addon also magically worked for me, you can just disable all their content with jei/crafttweaker/kubejs if you're not interested
